In [1]:
import numpy as np

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

%matplotlib inline

path = 'D:/CS/ML/'

train = pd.read_excel('%s%s' %(path, 'InputData.xlsx'))

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 12 columns):
飞机转场记录号    753 non-null object
到达
日期      753 non-null datetime64[ns]
到达
时刻      753 non-null object
到达
航班      753 non-null object
到达类型       753 non-null object
飞机型号       753 non-null object
出发
日期      753 non-null datetime64[ns]
出发
时刻      753 non-null object
出发
航班      753 non-null object
出发类型       753 non-null object
上线
机场      753 non-null object
下线
机场      753 non-null object
dtypes: datetime64[ns](2), object(10)
memory usage: 70.7+ KB

In [8]:
train.head(10)

,飞机转场记录号,到达 日期,到达 时刻,到达 航班,到达类型,飞机型号,出发 日期,出发 时刻,出发 航班,出发类型,上线 机场,下线 机场
0,PK001,2018-01-19,10:00:00,NV6294,D,321,2018-01-19,12:40:00,NV3118,I,QFL,NGN
1,PK002,2018-01-19,10:00:00,NV898,D,33E,2018-01-19,12:30:00,NV898,I,XOA,GDP
2,PK003,2018-01-19,10:05:00,GN0471,D,73A,2018-01-19,11:20:00,GN0460,D,AIB,AIB
3,PK004,2018-01-19,10:05:00,NV6513,D,320,2018-01-19,12:30:00,NV305,D,DUV,DUV
4,PK005,2018-01-19,10:10:00,GN0411,D,73H,2018-01-19,12:00:00,GN0236,D,TXB,SJA
5,PK006,2018-01-19,10:10:00,NV6443,D,325,2018-01-19,12:15:00,NV6144,I,TAY,JDO
6,PK007,2018-01-19,10:15:00,NV3120,D,73H,2018-01-19,11:15:00,NV3120,I,XVI,GTA
7,PK008,2018-01-19,10:15:00,NV632,D,325,2018-01-19,11:45:00,NV632,I,YJZ,OSU
8,PK009,2018-01-19,10:20:00,GN0495,D,73A,2018-01-19,11:30:00,GN0208,D,OOH,BPH
9,PK010,2018-01-19,10:20:00,NV323,I,325,2018-01-19,11:25:00,NV6390,D,NOM,AVI

In [13]:
train.columns

Index(['飞机转场记录号', '到达\n日期', '到达\n时刻', '到达\n航班', '到达类型', '飞机型号', '出发\n日期',
       '出发\n时刻', '出发\n航班', '出发类型', '上线\n机场', '下线\n机场'],
      dtype='object')

In [14]:
train.groupby(['到达\n日期'],['到达\n航班'])

TypeError: unhashable type: 'list'

In [15]:
train['到达\n航班']

0      NV6294
1       NV898
2      GN0471
3      NV6513
4      GN0411
5      NV6443
6      NV3120
7       NV632
8      GN0495
9       NV323
10      NV687
11     NV6731
12      NV820
13     GN0457
14      NV858
15     NV6713
16     GN0271
17      NV303
18      NV643
19      NV305
20     NV6148
21      NV639
22     NV6785
23     NV6535
24      NV841
25      NV835
26     NV6749
27      NV867
28     GN0253
29     NV3703
        ...
723     NV665
724     GN969
725     GN973
726     NV659
727     NV331
728    NV6700
729    NV3992
730    NV6135
731     *****
732    NV6577
733    NV6697
734    NV6579
735    NV6645
736    NV3620
737    NV6623
738    GN0631
739     NV628
740    GN0369
741     NV698
742    NV6773
743    GN0439
744    NV3513
745    NV6655
746    GN0571
747    NV6533
748    NV6163
749    GN0413
750    NV6479
751     NV837
752    NV6313
Name: 到达\n航班, Length: 753, dtype: object